name: Deploy Micro-Frontend to GCP

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Run Pipeline for Micro-frontends
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - app-shell
          - checkout
          - decide
          - explore
    steps:
      - name: Run script in changed folder
        run: |
          echo "Running script in ${{ matrix.folder }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if changes occurred in the folder
        id: folder_check
        run: |
          if git diff --name-only HEAD HEAD~1 | grep -q "^${{ matrix.folder }}/"; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        if: env.changes_detected == 'true'
        with:
          node-version: 'latest'


      - name: Install Dependencies
        if: env.changes_detected == 'true'
        run: |
          cd ${{ matrix.folder }}
          npm install

      - name: Build App
        if: env.changes_detected == 'true'
        run: |
          cd ${{ matrix.folder }}
          npm run build

      - uses: 'google-github-actions/auth@v2'
        if: env.changes_detected == 'true'
        with:
          credentials_json: '${{ secrets.GOOGLE_AUTH }}'

      - id: 'upload-files'
        if: env.changes_detected == 'true'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '${{ matrix.folder }}/dist'
          destination: 'tractor-v2-module-federation/${{ matrix.folder }}'
          parent: false
          gzip : false
          headers: |-
            cache-control: no-store
