name: Deploy App-Shell to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'  # Ensure the node version matches your project

      - name: Install Dependencies
        run: | 
          cd app-shell
          npm install

      - name: Build App
        run: |
          cd app-shell
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app-shell/dist  # Ensure this matches the build output folder
